<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Old test/hotspot/jtreg/vmTestbase/nsk/jdi/ExceptionRequest/exception/exception001.java</title>
    <link rel="stylesheet" href="../../../../../../../../style.css" />
  </head>
  <body>
    <pre>
  1 /*
  2  * Copyright (c) 2001, 2018, Oracle and/or its affiliates. All rights reserved.
  3  * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
  4  *
  5  * This code is free software; you can redistribute it and/or modify it
  6  * under the terms of the GNU General Public License version 2 only, as
  7  * published by the Free Software Foundation.
  8  *
  9  * This code is distributed in the hope that it will be useful, but WITHOUT
 10  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 11  * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 12  * version 2 for more details (a copy is included in the LICENSE file that
 13  * accompanied this code).
 14  *
 15  * You should have received a copy of the GNU General Public License version
 16  * 2 along with this work; if not, write to the Free Software Foundation,
 17  * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 18  *
 19  * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 20  * or visit www.oracle.com if you need additional information or have any
 21  * questions.
 22  */
 23 
 24 package nsk.jdi.ExceptionRequest.exception;
 25 
 26 import nsk.share.*;
 27 import nsk.share.jpda.*;
 28 import nsk.share.jdi.*;
 29 
 30 import com.sun.jdi.*;
 31 import com.sun.jdi.event.*;
 32 import com.sun.jdi.request.*;
 33 
 34 import java.util.*;
 35 import java.io.*;
 36 
 37 /**
 38  * The test for the implementation of an object of the type     &lt;BR&gt;
 39  * ExceptionRequest.                                            &lt;BR&gt;
 40  *                                                              &lt;BR&gt;
 41  * The test checks that results of the method                   &lt;BR&gt;
 42  * &lt;code&gt;com.sun.jdi.ExceptionRequest.exception()&lt;/code&gt;        &lt;BR&gt;
 43  * complies with its spec.                                      &lt;BR&gt;
 44  * &lt;BR&gt;
 45  * The test checks if a boolean value, an argument of the method        &lt;BR&gt;
 46  *    EventRequestManager.createExceptionRequest(),                     &lt;BR&gt;
 47  * is equal to one returned by the method                               &lt;BR&gt;
 48  *    ExceptionRequest.exception()                                      &lt;BR&gt;
 49  * The cases to test include a ReferenceType                            &lt;BR&gt;
 50  * mirroring NullPointerException, and null.                            &lt;BR&gt;
 51  * &lt;BR&gt;
 52  * The test has three phases and works as follows.                      &lt;BR&gt;
 53  * &lt;BR&gt;
 54  * In first phase,                                                      &lt;BR&gt;
 55  * upon launching debuggee&#39;s VM which will be suspended,                &lt;BR&gt;
 56  * a debugger waits for the VMStartEvent within a predefined            &lt;BR&gt;
 57  * time interval. If no the VMStartEvent received, the test is FAILED.  &lt;BR&gt;
 58  * Upon getting the VMStartEvent, it makes the request for debuggee&#39;s   &lt;BR&gt;
 59  * ClassPrepareEvent with SUSPEND_EVENT_THREAD, resumes the VM,         &lt;BR&gt;
 60  * and waits for the event within the predefined time interval.         &lt;BR&gt;
 61  * If no the ClassPrepareEvent received, the test is FAILED.            &lt;BR&gt;
 62  * Upon getting the ClassPrepareEvent,                                  &lt;BR&gt;
 63  * the debugger sets up the breakpoint with SUSPEND_EVENT_THREAD        &lt;BR&gt;
 64  * within debuggee&#39;s special methodForCommunication().                  &lt;BR&gt;
 65  * &lt;BR&gt;
 66  * In second phase to check the assertion,                              &lt;BR&gt;
 67  * the debugger and the debuggee perform the following.                 &lt;BR&gt;
 68  * - The debugger                                                       &lt;BR&gt;
 69  *   - gets ReferenceType value mirroring NullPointerException, &lt;BR&gt;
 70  *   - sets up two ExceptionRequests with the ReferenceType and null    &lt;BR&gt;
 71  *     values of the exception arguments,                               &lt;BR&gt;
 72  *   - gets the values of the Request with the method                   &lt;BR&gt;
 73  *     StepRequest.exception(), and                                     &lt;BR&gt;
 74  *   - compares the values.                                             &lt;BR&gt;
 75  * &lt;BR&gt;
 76  * In third phase, at the end of the test, the debuggee changes         &lt;BR&gt;
 77  * the value of the &quot;instruction&quot; which the debugger and debuggee       &lt;BR&gt;
 78  * use to inform each other of needed actions,  and both end.           &lt;BR&gt;
 79  * &lt;BR&gt;
 80  */
 81 
 82 public class exception001 {
 83 
 84     //----------------------------------------------------- templete section
 85     static final int PASSED = 0;
 86     static final int FAILED = 2;
 87     static final int PASS_BASE = 95;
 88 
 89     //----------------------------------------------------- templete parameters
 90     static final String
 91     sHeader1 = &quot;\n==&gt; nsk/jdi/ExceptionRequest/exception/exception001 &quot;,
 92     sHeader2 = &quot;--&gt; debugger: &quot;,
 93     sHeader3 = &quot;##&gt; debugger: &quot;;
 94 
 95     //----------------------------------------------------- main method
 96 
 97     public static void main (String argv[]) {
 98 
 99         int result = run(argv, System.out);
100 
101         System.exit(result + PASS_BASE);
102     }
103 
104     public static int run (String argv[], PrintStream out) {
105 
106         int exitCode = new exception001().runThis(argv, out);
107 
108         if (exitCode != PASSED) {
109             System.out.println(&quot;TEST FAILED&quot;);
110         }
111         return testExitCode;
112     }
113 
114     //--------------------------------------------------   log procedures
115 
116     private static Log  logHandler;
117 
118     private static void log1(String message) {
119         logHandler.display(sHeader1 + message);
120     }
121     private static void log2(String message) {
122         logHandler.display(sHeader2 + message);
123     }
124     private static void log3(String message) {
125         logHandler.complain(sHeader3 + message);
126     }
127 
128     //  ************************************************    test parameters
129 
130     private String debuggeeName =
131         &quot;nsk.jdi.ExceptionRequest.exception.exception001a&quot;;
132 
133     //====================================================== test program
134     //------------------------------------------------------ common section
135 
136     static Debugee          debuggee;
137     static ArgumentHandler  argsHandler;
138 
139     static int waitTime;
140 
141     static VirtualMachine      vm            = null;
142     static EventRequestManager eventRManager = null;
143     static EventQueue          eventQueue    = null;
144     static EventSet            eventSet      = null;
145     static EventIterator       eventIterator = null;
146 
147     static ReferenceType       debuggeeClass = null;
148 
149     static int  testExitCode = PASSED;
150 
151 
152     class JDITestRuntimeException extends RuntimeException {
153         JDITestRuntimeException(String str) {
154             super(&quot;JDITestRuntimeException : &quot; + str);
155         }
156     }
157 
158     //------------------------------------------------------ methods
159 
160     private int runThis (String argv[], PrintStream out) {
161 
162         argsHandler     = new ArgumentHandler(argv);
163         logHandler      = new Log(out, argsHandler);
164         Binder binder   = new Binder(argsHandler, logHandler);
165 
166         waitTime        = argsHandler.getWaitTime() * 60000;
167 
168         try {
169             log2(&quot;launching a debuggee :&quot;);
170             log2(&quot;       &quot; + debuggeeName);
171             if (argsHandler.verbose()) {
172                 debuggee = binder.bindToDebugee(debuggeeName + &quot; -vbs&quot;);
173             } else {
174                 debuggee = binder.bindToDebugee(debuggeeName);
175             }
176             if (debuggee == null) {
177                 log3(&quot;ERROR: no debuggee launched&quot;);
178                 return FAILED;
179             }
180             log2(&quot;debuggee launched&quot;);
181         } catch ( Exception e ) {
182             log3(&quot;ERROR: Exception : &quot; + e);
183             log2(&quot;       test cancelled&quot;);
184             return FAILED;
185         }
186 
187         debuggee.redirectOutput(logHandler);
188 
189         vm = debuggee.VM();
190 
191         eventQueue = vm.eventQueue();
192         if (eventQueue == null) {
193             log3(&quot;ERROR: eventQueue == null : TEST ABORTED&quot;);
194             vm.exit(PASS_BASE);
195             return FAILED;
196         }
197 
198         log2(&quot;invocation of the method runTest()&quot;);
199         switch (runTest()) {
200 
201             case 0 :  log2(&quot;test phase has finished normally&quot;);
202                       log2(&quot;   waiting for the debuggee to finish ...&quot;);
203                       debuggee.waitFor();
204 
205                       log2(&quot;......getting the debuggee&#39;s exit status&quot;);
206                       int status = debuggee.getStatus();
207                       if (status != PASS_BASE) {
208                           log3(&quot;ERROR: debuggee returned UNEXPECTED exit status: &quot; +
209                               status + &quot; != PASS_BASE&quot;);
210                           testExitCode = FAILED;
211                       } else {
212                           log2(&quot;......debuggee returned expected exit status: &quot; +
213                               status + &quot; == PASS_BASE&quot;);
214                       }
215                       break;
216 
217             default : log3(&quot;ERROR: runTest() returned unexpected value&quot;);
218 
219             case 1 :  log3(&quot;test phase has not finished normally: debuggee is still alive&quot;);
220                       log2(&quot;......forcing: vm.exit();&quot;);
221                       testExitCode = FAILED;
222                       try {
223                           vm.exit(PASS_BASE);
224                       } catch ( Exception e ) {
225                           log3(&quot;ERROR: Exception : &quot; + e);
226                       }
227                       break;
228 
229             case 2 :  log3(&quot;test cancelled due to VMDisconnectedException&quot;);
230                       log2(&quot;......trying: vm.process().destroy();&quot;);
231                       testExitCode = FAILED;
232                       try {
233                           Process vmProcess = vm.process();
234                           if (vmProcess != null) {
235                               vmProcess.destroy();
236                           }
237                       } catch ( Exception e ) {
238                           log3(&quot;ERROR: Exception : &quot; + e);
239                       }
240                       break;
241             }
242 
243         return testExitCode;
244     }
245 
246 
247    /*
248     * Return value: 0 - normal end of the test
249     *               1 - ubnormal end of the test
250     *               2 - VMDisconnectedException while test phase
251     */
252 
253     private int runTest() {
254 
255         try {
256             testRun();
257 
258             log2(&quot;waiting for VMDeathEvent&quot;);
259             getEventSet();
260             if (eventIterator.nextEvent() instanceof VMDeathEvent)
261                 return 0;
262 
263             log3(&quot;ERROR: last event is not the VMDeathEvent&quot;);
264             return 1;
265         } catch ( VMDisconnectedException e ) {
266             log3(&quot;ERROR: VMDisconnectedException : &quot; + e);
267             return 2;
268         } catch ( Exception e ) {
269             log3(&quot;ERROR: Exception : &quot; + e);
270             return 1;
271         }
272 
273     }
274 
275     private void testRun()
276                  throws JDITestRuntimeException, Exception {
277 
278         eventRManager = vm.eventRequestManager();
279 
280         ClassPrepareRequest cpRequest = eventRManager.createClassPrepareRequest();
281         cpRequest.setSuspendPolicy( EventRequest.SUSPEND_EVENT_THREAD);
282         cpRequest.addClassFilter(debuggeeName);
283 
284         cpRequest.enable();
285         vm.resume();
286         getEventSet();
287         cpRequest.disable();
288 
289         ClassPrepareEvent event = (ClassPrepareEvent) eventIterator.next();
290         debuggeeClass = event.referenceType();
291 
292         if (!debuggeeClass.name().equals(debuggeeName))
293            throw new JDITestRuntimeException(&quot;** Unexpected ClassName for ClassPrepareEvent **&quot;);
294 
295         log2(&quot;      received: ClassPrepareEvent for debuggeeClass&quot;);
296 
297         String bPointMethod = &quot;methodForCommunication&quot;;
298         String lineForComm  = &quot;lineForComm&quot;;
299 
300         ThreadReference   mainThread = threadByName(&quot;main&quot;);
301 
302         BreakpointRequest bpRequest = settingBreakpoint(mainThread,
303                                              debuggeeClass,
304                                             bPointMethod, lineForComm, &quot;zero&quot;);
305         bpRequest.enable();
306         vm.resume();
307 
308     //------------------------------------------------------  testing section
309 
310         log1(&quot;     TESTING BEGINS&quot;);
311 
312         EventRequest  eventRequest1 = null;
313         EventRequest  eventRequest2 = null;
314 
315         String fieldName = &quot;obj&quot;;
316         Value value = null;
317 
318         ReferenceType refObject = null;
319         ReferenceType exception = null;
320 
321         for (int i = 0; ; i++) {
322 
323             breakpointForCommunication();
324 
325             int instruction = ((IntegerValue)
326                                (debuggeeClass.getValue(debuggeeClass.fieldByName(&quot;instruction&quot;)))).value();
327 
328             if (instruction == 0) {
329                 vm.resume();
330                 break;
331             }
332 
333             log1(&quot;:::::: case: # &quot; + i);
334 
335             //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ variable part
336 
337             switch (i) {
338 
339               case 0:
340                      log2(&quot;......vm.resume();&quot;);
341                      vm.resume();
342 
343                      log2(&quot;......getting: refObject = debuggeeClass.getValue(debuggeeClass.fieldByName(fieldName));&quot;);
344                      value = debuggeeClass.getValue(debuggeeClass.fieldByName(fieldName));
345                      log2(&quot;      getting: refObject = (ReferenceType) value.type();&quot;);
346                      refObject = (ReferenceType) value.type();
347 
348                      log2(&quot;......setting up: eventRequest1 = setting25ExceptionRequest(refObject);&quot;);
349                      eventRequest1 = setting25ExceptionRequest(refObject);
350 
351                      log2(&quot;......getting: exception = ((ExceptionRequest) eventRequest1).exception();&quot;);
352                      exception = ((ExceptionRequest) eventRequest1).exception();
353 
354                      log2(&quot;      comparing ReferenceType objects&quot;);
355                      if ( !exception.equals(refObject) ) {
356                          testExitCode = FAILED;
357                          log3(&quot;ERROR: objects are not equal : &quot; + exception);
358                      }
359 
360                      log2(&quot;......setting up: eventRequest2 = setting25ExceptionRequest(null);&quot;);
361                      eventRequest2 = setting25ExceptionRequest(null);
362 
363                      log2(&quot;......getting: exception = ((ExceptionRequest) eventRequest2).exception();&quot;);
364                      exception = ((ExceptionRequest) eventRequest2).exception();
365 
366                      log2(&quot;      comparing to null&quot;);
367                      if ( exception != null ) {
368                          testExitCode = FAILED;
369                          log3(&quot;ERROR: exception is not the null : &quot; + exception);
370                      }
371 
372                       break;
373 
374               default:
375                       throw new JDITestRuntimeException(&quot;** default case 2 **&quot;);
376             }
377 
378 
379             //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
380         }
381         log1(&quot;    TESTING ENDS&quot;);
382         return;
383     }
384 
385     private ThreadReference threadByName(String name)
386                  throws JDITestRuntimeException {
387 
388         List         all = vm.allThreads();
389         ListIterator li  = all.listIterator();
390 
391         for (; li.hasNext(); ) {
392             ThreadReference thread = (ThreadReference) li.next();
393             if (thread.name().equals(name))
394                 return thread;
395         }
396         throw new JDITestRuntimeException(&quot;** Thread IS NOT found ** : &quot; + name);
397     }
398 
399    /*
400     * private BreakpointRequest settingBreakpoint(ThreadReference, ReferenceType,
401     *                                             String, String, String)
402     *
403     * It sets up a breakpoint at given line number within a given method in a given class
404     * for a given thread.
405     *
406     * Return value: BreakpointRequest object  in case of success
407     *
408     * JDITestRuntimeException   in case of an Exception thrown within the method
409     */
410 
411     private BreakpointRequest settingBreakpoint ( ThreadReference thread,
412                                                   ReferenceType testedClass,
413                                                   String methodName,
414                                                   String bpLine,
415                                                   String property)
416             throws JDITestRuntimeException {
417 
418         log2(&quot;......setting up a breakpoint:&quot;);
419         log2(&quot;       thread: &quot; + thread + &quot;; class: &quot; + testedClass +
420                         &quot;; method: &quot; + methodName + &quot;; line: &quot; + bpLine);
421 
422         List              alllineLocations = null;
423         Location          lineLocation     = null;
424         BreakpointRequest breakpRequest    = null;
425 
426         try {
427             Method  method  = (Method) testedClass.methodsByName(methodName).get(0);
428 
429             alllineLocations = method.allLineLocations();
430 
431             int n =
432                 ( (IntegerValue) testedClass.getValue(testedClass.fieldByName(bpLine) ) ).value();
433             if (n &gt; alllineLocations.size()) {
434                 log3(&quot;ERROR:  TEST_ERROR_IN_settingBreakpoint(): number is out of bound of method&#39;s lines&quot;);
435             } else {
436                 lineLocation = (Location) alllineLocations.get(n);
437                 try {
438                     breakpRequest = eventRManager.createBreakpointRequest(lineLocation);
439                     breakpRequest.putProperty(&quot;number&quot;, property);
440                     breakpRequest.addThreadFilter(thread);
441                     breakpRequest.setSuspendPolicy( EventRequest.SUSPEND_EVENT_THREAD);
442                 } catch ( Exception e1 ) {
443                     log3(&quot;ERROR: inner Exception within settingBreakpoint() : &quot; + e1);
444                     breakpRequest    = null;
445                 }
446             }
447         } catch ( Exception e2 ) {
448             log3(&quot;ERROR: ATTENTION:  outer Exception within settingBreakpoint() : &quot; + e2);
449             breakpRequest    = null;
450         }
451 
452         if (breakpRequest == null) {
453             log2(&quot;      A BREAKPOINT HAS NOT BEEN SET UP&quot;);
454             throw new JDITestRuntimeException(&quot;**FAILURE to set up a breakpoint**&quot;);
455         }
456 
457         log2(&quot;      a breakpoint has been set up&quot;);
458         return breakpRequest;
459     }
460 
461 
462     private void getEventSet()
463                  throws JDITestRuntimeException {
464         try {
465 //            log2(&quot;       eventSet = eventQueue.remove(waitTime);&quot;);
466             eventSet = eventQueue.remove(waitTime);
467             if (eventSet == null) {
468                 throw new JDITestRuntimeException(&quot;** TIMEOUT while waiting for event **&quot;);
469             }
470 //            log2(&quot;       eventIterator = eventSet.eventIterator;&quot;);
471             eventIterator = eventSet.eventIterator();
472         } catch ( Exception e ) {
473             throw new JDITestRuntimeException(&quot;** EXCEPTION while waiting for event ** : &quot; + e);
474         }
475     }
476 
477 
478     private void breakpointForCommunication()
479                  throws JDITestRuntimeException {
480 
481         log2(&quot;breakpointForCommunication&quot;);
482         getEventSet();
483 
484         if (eventIterator.nextEvent() instanceof BreakpointEvent)
485             return;
486 
487         throw new JDITestRuntimeException(&quot;** event IS NOT a breakpoint **&quot;);
488     }
489 
490     // ============================== test&#39;s additional methods
491 
492     private ExceptionRequest setting25ExceptionRequest ( ReferenceType refType )
493             throws JDITestRuntimeException {
494         try {
495             log2(&quot;......setting up ExceptionRequest:&quot;);
496 
497             ExceptionRequest
498             excr = eventRManager.createExceptionRequest(refType, true, true);
499 
500             log2(&quot;      ExceptionRequest has been set up&quot;);
501             return excr;
502         } catch ( Exception e ) {
503             log3(&quot;ERROR: ATTENTION: Exception within settingExceptionRequest() : &quot; + e);
504             log3(&quot;       ExceptionRequest HAS NOT BEEN SET UP&quot;);
505             throw new JDITestRuntimeException(&quot;** FAILURE to set up ExceptionRequest **&quot;);
506         }
507     }
508 
509 }
    </pre>
  </body>
</html>